---
meta:
  name: strongswan
  url: https://ci.vsphere.starkandwayne.com
  target: sw

  aws:
    access_key: (( vault "secret/aws/cfcommunity:access" ))
    secret_key: (( vault "secret/aws/cfcommunity:secret" ))
  github:
    owner: cloudfoundry-community
    repo:  strongswan-boshrelease
    private_key:  (( vault "secret/pipelines/strongswan-boshrelease/github:private" ))
    access_token: (( vault "secret/pipelines/strongswan-boshrelease/github:token" ))
  bosh-lite:
    target: https://10.58.111.44:25555
    deployment: strongswan-warden
  slack:
    webhook: (( vault "secret/pipelines/strongswan-boshrelease/slack:webhook" ))
    channel: "#cf-community-pipeline"

